package process

import (
	"cmp"
	"context"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/admirable-oss/hive/internal/environment"
	"github.com/admirable-oss/hive/internal/jsonfile"
)

// IDs are generated by newID (16 hex chars). Anything else can't exist, and
// rejecting it up front keeps user input out of filesystem paths.
var idPattern = regexp.MustCompile(`^[0-9a-f]{16}$`)

// FilesystemStore keeps each process next to its environment:
//
//	<root>/<env>/processes/<id>/process.json
//	<root>/<env>/processes/<id>/stdout.log
//	<root>/<env>/processes/<id>/stderr.log
type FilesystemStore struct {
	root string
}

func NewFilesystemStore(root string) *FilesystemStore {
	return &FilesystemStore{root: root}
}

func (s *FilesystemStore) processesDir(envID string) string {
	return filepath.Join(s.root, envID, "processes")
}

func (s *FilesystemStore) dir(p Process) string {
	return filepath.Join(s.processesDir(p.EnvironmentID), p.ID)
}

func (s *FilesystemStore) file(p Process) string { return filepath.Join(s.dir(p), "process.json") }

func (s *FilesystemStore) LogPaths(p Process) (stdout, stderr string) {
	return filepath.Join(s.dir(p), "stdout.log"), filepath.Join(s.dir(p), "stderr.log")
}

func (s *FilesystemStore) Create(_ context.Context, p Process) error {
	if err := os.MkdirAll(s.processesDir(p.EnvironmentID), 0o755); err != nil {
		return err
	}
	if err := os.Mkdir(s.dir(p), 0o755); err != nil {
		if errors.Is(err, fs.ErrExist) {
			return ErrAlreadyExists
		}
		return err
	}
	return jsonfile.Write(s.file(p), p)
}

func (s *FilesystemStore) Move(_ context.Context, p Process, envID string) (Process, error) {
	if !environment.ValidID(envID) {
		return Process{}, environment.ErrInvalidID
	}
	from := s.dir(p)
	moved := p
	moved.EnvironmentID = envID
	if err := os.MkdirAll(s.processesDir(envID), 0o755); err != nil {
		return Process{}, err
	}
	if err := os.Rename(from, s.dir(moved)); err != nil {
		return Process{}, err
	}
	if err := jsonfile.Write(s.file(moved), moved); err != nil {
		_ = os.Rename(s.dir(moved), from)
		return Process{}, err
	}
	return moved, nil
}

func (s *FilesystemStore) Update(_ context.Context, p Process) error {
	if _, err := os.Stat(s.file(p)); errors.Is(err, fs.ErrNotExist) {
		return ErrNotFound
	}
	return jsonfile.Write(s.file(p), p)
}

// Get finds a process by ID alone, so it scans each environment's directory.
func (s *FilesystemStore) Get(_ context.Context, id string) (Process, error) {
	if !idPattern.MatchString(id) {
		return Process{}, ErrNotFound
	}
	envs, err := os.ReadDir(s.root)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return Process{}, err
	}
	for _, env := range envs {
		var p Process
		if env.IsDir() && jsonfile.Read(s.file(Process{ID: id, EnvironmentID: env.Name()}), &p) == nil {
			return p, nil
		}
	}
	return Process{}, ErrNotFound
}

func (s *FilesystemStore) List(_ context.Context, envID string) ([]Process, error) {
	envIDs := []string{envID}
	if envID == "" {
		entries, err := os.ReadDir(s.root)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		envIDs = envIDs[:0]
		for _, e := range entries {
			if e.IsDir() {
				envIDs = append(envIDs, e.Name())
			}
		}
	} else if !environment.ValidID(envID) {
		return nil, environment.ErrInvalidID
	}

	procs := []Process{}
	for _, env := range envIDs {
		entries, err := os.ReadDir(s.processesDir(env))
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		for _, e := range entries {
			var p Process
			if e.IsDir() && jsonfile.Read(filepath.Join(s.processesDir(env), e.Name(), "process.json"), &p) == nil {
				procs = append(procs, p)
			}
		}
	}
	// Directory order is random (hex IDs); start order is stable for UIs.
	slices.SortStableFunc(procs, func(a, b Process) int {
		return cmp.Or(a.StartedAt.Compare(b.StartedAt), strings.Compare(a.ID, b.ID))
	})
	return procs, nil
}

func (s *FilesystemStore) logPath(p Process, stream Stream) string {
	stdout, stderr := s.LogPaths(p)
	if stream == StreamStderr {
		return stderr
	}
	return stdout
}

func (s *FilesystemStore) Tail(_ context.Context, p Process, stream Stream, n int) (string, error) {
	return tailLines(s.logPath(p, stream), n)
}

// tailLines returns the last n lines of the file at path, without the final
// newline. A missing file is an empty log.
func tailLines(path string, n int) (string, error) {
	f, err := os.Open(path)
	if errors.Is(err, fs.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return "", err
	}
	start, err := tailOffset(f, info.Size(), n)
	if err != nil {
		return "", err
	}
	data := make([]byte, info.Size()-start)
	if _, err := f.ReadAt(data, start); err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	return strings.TrimSuffix(string(data), "\n"), nil
}

// tailOffset returns where the last n lines of f (size bytes long) begin, or
// 0 for the whole file when n <= 0. It reads backwards in blocks, so the cost
// tracks n rather than the size of an ever-growing log.
func tailOffset(f io.ReaderAt, size int64, n int) (int64, error) {
	if n <= 0 || size == 0 {
		return 0, nil
	}
	const block = 8 << 10
	buf := make([]byte, block)
	end := size
	// A newline that ends the file terminates the last line; it does not
	// start a new one, so it is skipped.
	newlines := 0
	skipFinal := true
	for end > 0 {
		start := max(0, end-block)
		chunk := buf[:end-start]
		if _, err := f.ReadAt(chunk, start); err != nil && !errors.Is(err, io.EOF) {
			return 0, err
		}
		for i := len(chunk) - 1; i >= 0; i-- {
			if chunk[i] != '\n' {
				skipFinal = false
				continue
			}
			if skipFinal {
				skipFinal = false
				continue
			}
			if newlines++; newlines == n {
				return start + int64(i) + 1, nil
			}
		}
		end = start
	}
	return 0, nil
}
