package process

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/admirable-oss/hive/internal/environment"
	"github.com/admirable-oss/hive/internal/jsonfile"
)

// IDs are generated by newID (16 hex chars). Anything else can't exist, and
// rejecting it up front keeps user input out of filesystem paths.
var idPattern = regexp.MustCompile(`^[0-9a-f]{16}$`)

// FilesystemStore keeps each process next to its environment:
//
//	<root>/<env>/processes/<id>/process.json
//	<root>/<env>/processes/<id>/stdout.log
//	<root>/<env>/processes/<id>/stderr.log
type FilesystemStore struct {
	root string
}

func NewFilesystemStore(root string) *FilesystemStore {
	return &FilesystemStore{root: root}
}

func (s *FilesystemStore) processesDir(envID string) string {
	return filepath.Join(s.root, envID, "processes")
}

func (s *FilesystemStore) dir(p Process) string {
	return filepath.Join(s.processesDir(p.EnvironmentID), p.ID)
}

func (s *FilesystemStore) file(p Process) string { return filepath.Join(s.dir(p), "process.json") }

func (s *FilesystemStore) LogPaths(p Process) (stdout, stderr string) {
	return filepath.Join(s.dir(p), "stdout.log"), filepath.Join(s.dir(p), "stderr.log")
}

func (s *FilesystemStore) Create(_ context.Context, p Process) error {
	if err := os.MkdirAll(s.processesDir(p.EnvironmentID), 0o755); err != nil {
		return err
	}
	if err := os.Mkdir(s.dir(p), 0o755); err != nil {
		if errors.Is(err, fs.ErrExist) {
			return ErrAlreadyExists
		}
		return err
	}
	return jsonfile.Write(s.file(p), p)
}

func (s *FilesystemStore) Update(_ context.Context, p Process) error {
	if _, err := os.Stat(s.file(p)); errors.Is(err, fs.ErrNotExist) {
		return ErrNotFound
	}
	return jsonfile.Write(s.file(p), p)
}

// Get finds a process by ID alone, so it scans each environment's directory.
func (s *FilesystemStore) Get(_ context.Context, id string) (Process, error) {
	if !idPattern.MatchString(id) {
		return Process{}, ErrNotFound
	}
	envs, err := os.ReadDir(s.root)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return Process{}, err
	}
	for _, env := range envs {
		var p Process
		if env.IsDir() && jsonfile.Read(s.file(Process{ID: id, EnvironmentID: env.Name()}), &p) == nil {
			return p, nil
		}
	}
	return Process{}, ErrNotFound
}

func (s *FilesystemStore) List(_ context.Context, envID string) ([]Process, error) {
	envIDs := []string{envID}
	if envID == "" {
		entries, err := os.ReadDir(s.root)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		envIDs = envIDs[:0]
		for _, e := range entries {
			if e.IsDir() {
				envIDs = append(envIDs, e.Name())
			}
		}
	} else if !environment.ValidID(envID) {
		return nil, environment.ErrInvalidID
	}

	procs := []Process{}
	for _, env := range envIDs {
		entries, err := os.ReadDir(s.processesDir(env))
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		for _, e := range entries {
			var p Process
			if e.IsDir() && jsonfile.Read(filepath.Join(s.processesDir(env), e.Name(), "process.json"), &p) == nil {
				procs = append(procs, p)
			}
		}
	}
	// Directory order is random (hex IDs); start order is stable for UIs.
	slices.SortStableFunc(procs, func(a, b Process) int {
		return cmp.Or(a.StartedAt.Compare(b.StartedAt), strings.Compare(a.ID, b.ID))
	})
	return procs, nil
}

func (s *FilesystemStore) Tail(_ context.Context, p Process, n int) (string, error) {
	stdout, _ := s.LogPaths(p)
	return tailLines(stdout, n)
}

// tailLines returns the last n lines of the file at path. It reads backwards
// in blocks, so the cost tracks n rather than the size of an ever-growing log.
func tailLines(path string, n int) (string, error) {
	f, err := os.Open(path)
	if errors.Is(err, fs.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	defer f.Close()

	if n <= 0 {
		data, err := io.ReadAll(f)
		return string(data), err
	}
	info, err := f.Stat()
	if err != nil {
		return "", err
	}

	const block = 8 << 10
	var buf []byte
	for end := info.Size(); end > 0; {
		start := max(0, end-block)
		chunk := make([]byte, end-start)
		if _, err := f.ReadAt(chunk, start); err != nil && !errors.Is(err, io.EOF) {
			return "", err
		}
		buf = append(chunk, buf...)
		end = start
		// n complete lines need n newlines, ignoring the one ending the file.
		if bytes.Count(bytes.TrimSuffix(buf, []byte("\n")), []byte("\n")) >= n {
			break
		}
	}

	lines := strings.Split(strings.TrimSuffix(string(buf), "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n"), nil
}
